version: '3.8'

services:
  car-service:
    build:
      context: ./services/car-service
      dockerfile: Dockerfile
    container_name: car-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=car_db
      - DB_USER=simpi
      - DB_PASSWORD=1231
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - car-network

networks:
  car-network:
    driver: bridge
